package com.bt.shopguide.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class Category implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORYS.id
     *
     * @mbggenerated Tue Oct 10 10:40:57 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORYS.name
     *
     * @mbggenerated Tue Oct 10 10:40:57 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORYS.parent_id
     *
     * @mbggenerated Tue Oct 10 10:40:57 CST 2017
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORYS.seq
     *
     * @mbggenerated Tue Oct 10 10:40:57 CST 2017
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORYS.create_time
     *
     * @mbggenerated Tue Oct 10 10:40:57 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORYS.update_time
     *
     * @mbggenerated Tue Oct 10 10:40:57 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORYS.id
     *
     * @return the value of CATEGORYS.id
     *
     * @mbggenerated Tue Oct 10 10:40:57 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORYS.id
     *
     * @param id the value for CATEGORYS.id
     *
     * @mbggenerated Tue Oct 10 10:40:57 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORYS.name
     *
     * @return the value of CATEGORYS.name
     *
     * @mbggenerated Tue Oct 10 10:40:57 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORYS.name
     *
     * @param name the value for CATEGORYS.name
     *
     * @mbggenerated Tue Oct 10 10:40:57 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORYS.parent_id
     *
     * @return the value of CATEGORYS.parent_id
     *
     * @mbggenerated Tue Oct 10 10:40:57 CST 2017
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORYS.parent_id
     *
     * @param parentId the value for CATEGORYS.parent_id
     *
     * @mbggenerated Tue Oct 10 10:40:57 CST 2017
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORYS.seq
     *
     * @return the value of CATEGORYS.seq
     *
     * @mbggenerated Tue Oct 10 10:40:57 CST 2017
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORYS.seq
     *
     * @param seq the value for CATEGORYS.seq
     *
     * @mbggenerated Tue Oct 10 10:40:57 CST 2017
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORYS.create_time
     *
     * @return the value of CATEGORYS.create_time
     *
     * @mbggenerated Tue Oct 10 10:40:57 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORYS.create_time
     *
     * @param createTime the value for CATEGORYS.create_time
     *
     * @mbggenerated Tue Oct 10 10:40:57 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORYS.update_time
     *
     * @return the value of CATEGORYS.update_time
     *
     * @mbggenerated Tue Oct 10 10:40:57 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORYS.update_time
     *
     * @param updateTime the value for CATEGORYS.update_time
     *
     * @mbggenerated Tue Oct 10 10:40:57 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}