package com.bt.shopguide.dao.entity;

import java.util.Date;

public class GoodsErrors {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_ERRORS.id
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_ERRORS.reason
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_ERRORS.create_time
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_ERRORS.json
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    private byte[] json;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_ERRORS.id
     *
     * @return the value of GOODS_ERRORS.id
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_ERRORS.id
     *
     * @param id the value for GOODS_ERRORS.id
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_ERRORS.reason
     *
     * @return the value of GOODS_ERRORS.reason
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_ERRORS.reason
     *
     * @param reason the value for GOODS_ERRORS.reason
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_ERRORS.create_time
     *
     * @return the value of GOODS_ERRORS.create_time
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_ERRORS.create_time
     *
     * @param createTime the value for GOODS_ERRORS.create_time
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_ERRORS.json
     *
     * @return the value of GOODS_ERRORS.json
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    public byte[] getJson() {
        return json;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_ERRORS.json
     *
     * @param json the value for GOODS_ERRORS.json
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    public void setJson(byte[] json) {
        this.json = json;
    }
}