package com.bt.shopguide.dao.entity;

import java.util.Date;

public class GoodsDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_DETAIL.id
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_DETAIL.goods_id
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    private Long goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_DETAIL.create_time
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_DETAIL.content_html
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    private byte[] contentHtml;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_DETAIL.id
     *
     * @return the value of GOODS_DETAIL.id
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_DETAIL.id
     *
     * @param id the value for GOODS_DETAIL.id
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_DETAIL.goods_id
     *
     * @return the value of GOODS_DETAIL.goods_id
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_DETAIL.goods_id
     *
     * @param goodsId the value for GOODS_DETAIL.goods_id
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_DETAIL.create_time
     *
     * @return the value of GOODS_DETAIL.create_time
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_DETAIL.create_time
     *
     * @param createTime the value for GOODS_DETAIL.create_time
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_DETAIL.content_html
     *
     * @return the value of GOODS_DETAIL.content_html
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    public byte[] getContentHtml() {
        return contentHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_DETAIL.content_html
     *
     * @param contentHtml the value for GOODS_DETAIL.content_html
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    public void setContentHtml(byte[] contentHtml) {
        this.contentHtml = contentHtml;
    }
}