package com.bt.shopguide.dao.mapper;

import com.bt.shopguide.dao.entity.GoodsDetail;

public interface GoodsDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_DETAIL
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_DETAIL
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    int insert(GoodsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_DETAIL
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    int insertSelective(GoodsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_DETAIL
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    GoodsDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_DETAIL
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    int updateByPrimaryKeySelective(GoodsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_DETAIL
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(GoodsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_DETAIL
     *
     * @mbggenerated Tue Sep 26 09:43:22 CST 2017
     */
    int updateByPrimaryKey(GoodsDetail record);
}