package com.bt.shopguide.dao.mapper;

import com.bt.shopguide.dao.entity.GoodsErrors;

public interface GoodsErrorsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_ERRORS
     *
     * @mbggenerated Tue Sep 26 12:35:49 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_ERRORS
     *
     * @mbggenerated Tue Sep 26 12:35:49 CST 2017
     */
    int insert(GoodsErrors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_ERRORS
     *
     * @mbggenerated Tue Sep 26 12:35:49 CST 2017
     */
    int insertSelective(GoodsErrors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_ERRORS
     *
     * @mbggenerated Tue Sep 26 12:35:49 CST 2017
     */
    GoodsErrors selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_ERRORS
     *
     * @mbggenerated Tue Sep 26 12:35:49 CST 2017
     */
    int updateByPrimaryKeySelective(GoodsErrors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_ERRORS
     *
     * @mbggenerated Tue Sep 26 12:35:49 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(GoodsErrors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_ERRORS
     *
     * @mbggenerated Tue Sep 26 12:35:49 CST 2017
     */
    int updateByPrimaryKey(GoodsErrors record);
}