package com.bt.shopguide.dao.mapper;

import com.bt.shopguide.dao.entity.Hotword;

import java.util.List;

public interface HotwordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTWORDS
     *
     * @mbggenerated Tue Oct 10 09:25:32 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTWORDS
     *
     * @mbggenerated Tue Oct 10 09:25:32 CST 2017
     */
    int insert(Hotword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTWORDS
     *
     * @mbggenerated Tue Oct 10 09:25:32 CST 2017
     */
    int insertSelective(Hotword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTWORDS
     *
     * @mbggenerated Tue Oct 10 09:25:32 CST 2017
     */
    Hotword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTWORDS
     *
     * @mbggenerated Tue Oct 10 09:25:32 CST 2017
     */
    int updateByPrimaryKeySelective(Hotword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTWORDS
     *
     * @mbggenerated Tue Oct 10 09:25:32 CST 2017
     */
    int updateByPrimaryKey(Hotword record);

    List<Hotword> getTopN(Integer n);
}